* Look up critical values robust to bandwidth-snooping

The =R= function =LookUpCV(ratio, kernel, onesided, level)= looks up appropriate
critical values for constructing confidence intervals that are valid uniformly
over a pre-specified range of bandwidth.

- The parameter =ratio= is the ratio of maximum to minimum bandwidth that the
  researcher has tried (between 1 and 100).
- Possible kernel choices are:
  1. =uniform=, =triangular=, and =epanechnikov= for local constant
     (Nadaraya-Watson) regression in the interior of the support of the
     regressor.
  2. =luniform=, =ltriangular=, and =lepanechnikov= for local linear regression
     at the boundary of the support of the regressor using the uniform,
     triangular, or Epanechnikov kernel (for instance, when estimating sharp or
     fuzzy regression discontinuity).
  3. =quniform=, =qtriangular=, and =qepanechnikov= for local quadratic
     regression at the boundary of the support of the regressor using the
     uniform, triangular, or Epanechnikov kernel (for instance, when estimating
     sharp or fuzzy regression discontinuity).
- =onesided= is a flag for whether the critical value corresponds to a one-sided
  confidence interval (=FALSE= by default)
- =level= specifies the confidence level (=0.95=) by default, other choices are
  =0.90= and =0.99=

See section 3.1 in Armstrong and Kolesár, 2014 "A Simple Adjustment for
Bandwidth Snooping" for kernel definitions implementation details
